# Build Declarations
## The site was built using MkDocs as the framework, and custom styling was referenced from Eureka! & Wcowin's Web authors, thanks for sharing the technology!
## 网站构建使用的 MkDocs 作为框架，另外自定义样式参考于 Eureka! & Wcowin's Web 两位作者，感谢技术分享！
## Material for MkDocs https://squidfunk.github.io/mkdocs-material/setup/
## Eureka! http://www.cuishuaiwen.com:8000
## Wcowin's Web https://wcowin.work

# Build Methods
## MkDocs-Material is deployed through Docker. In addition, the official image lacks relevant Plugins, so we will refactor it first
## 通过 Docker 部署 MkDocs-Material，另外官方镜像缺少相关 Plugins，故先行重构

# Test & Build
## docker run --rm -it --name docs -v ${PWD}:/docs -p 8000:8000 yuikuen/mkdocs-material:9.5.25 serve -a 0.0.0.0:8000
## docker run --rm -it --name docs -v ${PWD}:/docs -p 8000:8000 yuikuen/mkdocs-material:9.5.25 build

# Basic Info
site_name: Yuen's Info Silo          # 网站名字
site_url: http://47.113.102.164:8000 # 网站地址
site_author: Mr.Yuen                 # 作者名字
site_description: >-                 # 项目描述
  mó dāo bú wù kǎn chái gōng

# 版权信息
copyright: >-
  Copyright &copy; 2024 - now | 🔞 Yuen / All Rights Reserved. | 
  <a href="https://beian.miit.gov.cn/" target="_blank">粤ICP备202425834号</a>
# 仓库信息
edit_uri: edit/main/docs/             # 定义 URL 指向一个有效的子文件目录
repo_name: yuikuen/infosilo.github.io # 右上角仓库名字 & 地址
repo_url: https://github.com/yuikuen/infosilo.github.io.git


# Theme Styles
## 参考 https://squidfunk.github.io/mkdocs-material/setup
theme:
  name: material        # 主题名称
  custom_dir: overrides # 主题自定义目录(会覆盖官方默认样式)
  # [Colors]
  palette:
    #primary: light blue
    #accent: light green
    
    # 日夜切换
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto # 自动图标
        name: Switch to light mode     # 悬浮提示语
    - media: "(prefers-color-scheme: light)"
      scheme: default                  # 日间模式
      primary: indigo                  # 日间颜色
      accent: cyan                     # 高亮色-链接/标题等
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate                    # 夜间模式
      primary: black                   # 夜间颜色
      accent: deep purple              # 高亮色-链接/标题等
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # [Font]
  font:
    text: Roboto
    code: Roboto Mono
  # [Language]
  language: en
  # [Icons]
  logo: assets/images/logo.png       # 图站Logo,左上角图 https://cdn0.iconfinder.com/data/icons/essential-pack-4/512/11-2-1024.png
  favicon: assets/images/favicon.png # 浏览器菜单栏上图标 https://cdn1.iconfinder.com/data/icons/gestureworks_gesture_glyphs/512/stroke_letter_y_lowercase_gestureworks.png
  icon:
    previous: fontawesome/solid/angles-left # 页脚导航:上一页
    next: fontawesome/solid/angles-right    # 页脚导航:下一页
    edit: material/pencil                   # 文章编辑图标
    view: material/eye                      # 文章查看图标
    repo: fontawesome/brands/github         # 右上角GitHub图标
    tag:                                    # 自定义标签
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    admonition:
      tip: fontawesome/solid/bullhorn       # 自定义警告标志
  # [Features]
  features:
    # 导航
    #- navigation.instant         # 瞬间加载(多语言切换会导致跳回首页)
    - navigation.instant.prefetch # 预先加载
    - navigation.instant.progress # 进度显示
    - navigation.tracking         # 锚点跟踪(地址栏中的URL会自动更新为目录中突出显示的活动锚点)
    - navigation.tabs             # 顶部菜单(顶级索引被作为Tab)
    - navigation.tabs.sticky      # 顶部菜单始终可见(Tab滚动始终可见)
    - navigation.sections         # 侧边栏中以组的形式呈现
    - navigation.expand           # 侧边栏展开,默认展开导航栏
    - navigation.path             # 页面标题上方呈现具体导航路径
    #- navigation.prune           # 仅显示只构建导航树的可见部分
    - navigation.indexes          # 启用节索引页后,可以将文档直接附加到节
    - navigation.top              # 滚动显示返回顶部按钮
    - toc.follow                  # 目录跟踪-页面右侧小目录
    #- toc.integrate              # 目录跟踪-页面左侧大目录
    # 搜索-需启用plugins.search插件
    - search.suggest              # 搜索建议
    - search.highlight            # 搜索高亮显示
    - search.share                # 搜索分享按钮
    # 页眉
    - header.autohide             # 自动隐藏
    - announce.dismiss            # 可点X关闭临时公告
    # 页脚
    - navigation.footer           # 底部导航栏
    # 代码
    - content.action.edit         # 支持代码编译
    - content.action.view         # 支持代码查看
    - content.tabs.link           # 多标签链接
    - content.code.copy           # 代码码内容复制
    - content.code.select         # 特定行突出显示
    - content.code.annotate       # 代码注释
    - content.tooltips            # 工具提示:如链接[]()或[][]
    - content.footnote.tooltips   # 脚注呈现

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])' # 提高搜索索引精确度
  # 需pip install mkdocs-exclude-search,搜索排除某文件
  #- exclude-search:
  #    exclude:
  #      - dir/*
  #- git-authors
  - offline # 离线插件
  #- social # 社交插件,开启后无法运行,暂未知
  #- blog   # 博客插件
  #- rss    # 订阅插件
  #- tags   # 标签插件
  
  # 多语言翻译插件 https://github.com/ultrabug/mkdocs-static-i18n
  # 需：pip install mkdocs-static-i18n
  # 通过文件后缀识别,如filename.zh.md/filename.en.md;另外官方作者建议通过目录来区分，如en/zh
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true
          nav_translations: # 注意,导航栏中所有需翻译的标题和副标都可放这里,但不能缩进
            Home: 首页
            About: 关于
            Notes: 笔记
            Tools: 工具
            Giscus: 留言
            # 参考例子,仅菜单栏翻译
            #Web Site: 网站
            #Hugo on Ubuntu: Ubuntu 部署 Hugo
            #Docker deploys MkDocs: 使用 Docker 部署 MkDocs
            #Beautify style: 美化样式 
  # !!git相关插件需要放在i18n下面,不然会报错无法serve!!
  # 每篇文章底部显示
  # 需：pip install mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized: # 文章底部显示创建/更新时间
      enabled: true
      type: iso_date
      enable_creation_date: true
      fallback_to_build_date: true
      exclude:                   # 排除以下文章
        - index.md
   
  # 需：pip install mkdocs-git-committers-plugin-2 并通过 GitHub Actions 方式提交
  #- git-committers:              # 呈现贡献者的GitHub头像
  #    enabled: true              # 关闭 !ENV [CI, false]
  #    repository: yuikuen/infosilo.github.io
  #    branch: main
  #    exclude:                   # 排除以下文章
  #      - index.md

# Extensions
# 主要是 MD 文章的相关 Py 渲染功能(具体参考官网)
# 参考 https://squidfunk.github.io/mkdocs-material/setup/extensions/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:        # 允许呈现块和内联块方程
      generic: true
  - pymdownx.betterem:          # 开启特殊字符强调MD中的文本
      smart_enable: all
  - pymdownx.caret              # 开启插入符号
  - pymdownx.mark               # 开启标记符号
  - pymdownx.tilde              # 开启波浪形扩展
  - pymdownx.critic:            # 突出显示文档中添加,删除或更新的部分
      mode: view
  - pymdownx.details            # 可展开详细说明
  - pymdownx.emoji:             # Emoji扩展-图标/表情符号等
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:         # 代码块高亮
      anchor_linenums: true
      linenums: true            # 显示行号
      #auto_title: true         # 显示编程语言名称
      line_spans: __span        # 代码块的每一行都被包装在一个span中
      pygments_lang_class: true # CSS类来标识代码块的语言
  - pymdownx.inlinehilite       # 增加了对内联代码块语法高亮显示的支持
  - pymdownx.keys               # 允许键盘键和组合的呈现
  - pymdownx.smartsymbols       # 字符序列转换为相应的符号，例如版权符号或分数
  - pymdownx.snippets           # 将任意文件中的内容嵌入文档(包括其他文档或源文件)的功能
  - pymdownx.superfences:       # 允许任意嵌套代码和内容块，包括警告、选项卡、列表和所有其他元素
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true     # 允许使用内容选项卡
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true     # 允许使用GitHub风味Markdown启发的任务列表，遵循相同的语法约定
  - pymdownx.arithmatex:        # MathJax1数学公式支持
      generic: true

# Extra
extra:
  # 官方多语言切换,以目录区分;因启用i18n插件,此注释
  #alternate:
  #  - name: English
  #    link: /en/
  #  - name: Chinese
  #    link: /zh/
  #    lang: zh
  # 页面状态标识符
  status:
    new: Recently added
    deprecated: Deprecated
  # 网站分析
  analytics:
    # [Google Analytics-谷歌分析]
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    # [Feedback-每篇页面底部反馈]
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
          # using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # [Cookie-同意解决方案]
  #consent:
  #  title: Cookie consent
  #  description: >- 
  #    We use cookies to recognize your repeated visits and preferences, as well
  #    as to measure the effectiveness of our documentation and whether users
  #    find what they're searching for. With your consent, you're helping us to
  #    make our documentation better.
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  generator: true # 是否保留'Material for MkDocs'
  # [Social-社交链接]
  ## 官方图标 https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo-icon-bundled
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yuikuen
      name: GitHub
    #- icon: fontawesome/brands/gitlab
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/yuikuen
    - icon: fontawesome/regular/envelope
      link: mailto:<yuikuen.yuen@gmail.com>
      name: G-Email
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/YuikuenY
      name: X-Twitter
    - icon: fontawesome/brands/weixin
      link: assets/images/WeChat.jpg
    - icon: fontawesome/brands/qq
      link: assets/images/QQ.jpg
      name: QQ

# [额外样式](不会前端,具体不清楚)
extra_css:
  - assets/stylesheets/extra.css # 官方样式:Pied Piper自定义类型的警告
extra_javascript:
  - assets/javascripts/mathjax.js # 公式
  #- assets/javascripts/embed-pdf.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Nav
# 目录清单,主/副/文章均在此编辑,另还需补充i18n清单
nav:
  - Home:
    - index.md
    - About: home/about.md
  - Notes:
    - Web Site:
        - Hugo:
            Hugo on Ubuntu: notes/Hugo/hugo-on-ubuntu.md
        - MkDocs:
            Docker deploys MkDocs: notes/MkDocs/docker-mkdocs.md
            Beautify style:
              - Top bulletin board: notes/MkDocs/beauty-board.md
              - Comment System: notes/MkDocs/comment-system.md
  - Tools:
    - VMware:
      - VMware Free: tools/VMware/vmware-free.md
  - Giscus:
    - giscus.md
