# Build Methods（构建方法）
## 使用 MkDocs-Material 官方镜像安装 Plugins，再通过 Docker 构建部署
# Test & Build（测试&构建）
## docker run --rm -it --name docs -v ${PWD}:/docs -p 8000:8000 yuikuen/mkdocs-material:9.5.25 serve -a 0.0.0.0:8000
## docker run --rm -it --name docs -v ${PWD}:/docs -p 8000:8000 yuikuen/mkdocs-material:9.5.25 build

# Site Info（站点信息）
site_name: Yc's Info_Silo
site_url: https://www.17121203.xyz
site_author: Mr.Yuen
site_description: >-
  mó dāo bú wù kǎn chái gōng

# Repo Info（仓库信息）
edit_uri: edit/main/docs/
repo_name: yuikuen/infosilo.github.io
repo_url: https://github.com/yuikuen/infosilo.github.io.git

# Copyright（版权声明）
copyright: >-
  Copyright &copy; 2024 - now | 🔞 Yuen / All Rights Reserved. |
  <a href="https://beian.miit.gov.cn/" target="_blank">粤ICP备202425834号</a> 

# Theme Styles（主题样式）
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/Devops.png
  favicon: assets/images/favicon.png
  # 可自行替换默认图标，图标可从官网搜索
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  icon:
    previous: fontawesome/solid/angles-left # 页脚导航:上一页
    next: fontawesome/solid/angles-right    # 页脚导航:下一页
    edit: material/pencil                   # 文章编辑图标
    view: material/eye                      # 文章查看图标
    repo: fontawesome/brands/github         # 右上角GitHub图标
    admonition:                             # 警告标签自定义
      ai: simple/openai
      example: material/hexagon-multiple
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto # 自动图标
        name: Switch to light mode     # 悬浮提示语
    - media: "(prefers-color-scheme: light)"
      scheme: default                  # 日间模式
      primary: indigo                  # 日间颜色
      accent: cyan                     # 高亮色-链接/标题等
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate                    # 夜间模式
      primary: black                   # 夜间颜色
      accent: deep purple              # 高亮色-链接/标题等
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  language: en           # 默认语言
  font:
    text: Roboto         # 文本字体
    code: JetBrains Mono # 代码字体
  features:
    # 导航
    - navigation.tabs             # 顶部菜单(顶级索引被作为Tab)
    - navigation.tabs.sticky      # 顶部菜单始终可见(Tab滚动始终可见)
    - navigation.instant.prefetch # 预先加载
    - navigation.instant.progress # 进度显示
    # 菜单
    - navigation.tracking         # 锚点跟踪(地址栏中的URL会自动更新为目录中突出显示的活动锚点)
   #- navigation.sections         # 侧边栏中以组的形式呈现所有
   #- navigation.without          # 侧边栏展开,默认展开导航栏
    - navigation.path             # 页面标题上方呈现具体导航路径
    - navigation.indexes          # 启用节索引页后,可以将文档直接附加到节
    - navigation.top              # 滚动显示返回顶部按钮
    - toc.follow                  # 目录跟踪-页面右侧小目录
    # 搜索(*plugins.search)
    - search.suggest              # 搜索建议
    - search.highlight            # 高亮提醒
    - search.share                # 分享按钮
    # 页眉
    - header.autohide             # 自动隐藏
    - announce.dismiss            # 可点X关闭临时公告,对应overrides/main.html
    # 页脚
    - navigation.footer           # 底部导航
    # 代码
    - content.tabs.link           # 多标签链接
    - content.code.copy           # 代码码内容复制
    - content.code.select         # 特定行突出显示
    - content.code.annotate       # 代码注释
    - content.tooltips            # 工具提示:如链接[]()或[][]
    - content.footnote.tooltips   # 脚注呈现

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - offline:
      enabled: !ENV [OFFLINE, false]
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true
          nav_translations:
            Home: 首页
            Grammar: 语法
            Item: 项目
           #Network: 网络
            System: 系统
            Software: 软件
            Fun: 乐趣
            Giscus: 留言
  # git插件需要放在i18n下面,否则报错无法serve
  - git-revision-date-localized:
      enabled: true # 每篇文章底部显示创建/更新时间
      type: iso_date
      enable_creation_date: true
      fallback_to_build_date: true
      exclude: # 排除以下文章
        - index.md

# MD文章相关PY渲染功能,参考https://squidfunk.github.io/mkdocs-material/setup/extensions/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:        # 允许呈现块和内联块方程
      generic: true
  - pymdownx.betterem:          # 开启特殊字符强调MD中的文本
      smart_enable: all
  - pymdownx.caret              # 开启插入符号
  - pymdownx.mark               # 开启标记符号
  - pymdownx.tilde              # 开启波浪形扩展
  - pymdownx.critic:            # 突出显示文档中添加,删除或更新的部分
      mode: view
  - pymdownx.details            # 可展开详细说明
  - pymdownx.emoji:             # Emoji扩展-图标/表情符号等
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:         # 代码块高亮
      anchor_linenums: true
      linenums: true            # 显示行号
      #auto_title: true         # 显示编程语言名称
      line_spans: __span        # 代码块的每一行都被包装在一个span中
      pygments_lang_class: true # CSS类来标识代码块的语言
  - pymdownx.inlinehilite       # 增加了对内联代码块语法高亮显示的支持
  - pymdownx.keys               # 允许键盘键和组合的呈现
  - pymdownx.smartsymbols       # 字符序列转换为相应的符号，例如版权符号或分数
  - pymdownx.snippets           # 将任意文件中的内容嵌入文档(包括其他文档或源文件)的功能
  - pymdownx.superfences:       # 允许任意嵌套代码和内容块，包括警告、选项卡、列表和所有其他元素
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true     # 允许使用内容选项卡
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true     # 允许使用GitHub风味Markdown启发的任务列表，遵循相同的语法约定
  - pymdownx.arithmatex:        # MathJax1数学公式支持
      generic: true

extra:
  # 文章状态
  status:
    new: Recently added
    deprecated: Deprecated
    happy: Happy
  # 网站分析
  analytics:
    # [Google Analytics-谷歌分析]
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    # [Feedback-每篇页面底部反馈]
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  generator: true # 是否保留'Material for MkDocs'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yuikuen
      name: GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/yuikuen
      name: Docker
    - icon: fontawesome/regular/envelope
      link: mailto:<yuikuen.yuen@gmail.com>
      name: G-Email
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/YuikuenY
      name: X-Twitter

# 扩展插件
extra_javascript:
  # Arithmatex
  - assets/javascripts/mathjax.js 
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # KaTeX
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  # unkonw
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 自定义样式
extra_css:
  - assets/stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

# 文章目录
nav:
  - Home:
    - index.md
  - Grammar:
    - Bash:
      - Auto Clean Cache: Notes/Grammar/Bash/auto-clean-cache.md
  - Item:
    - Notes/Item/index.md
    - AI:
      - Deploy ChatGPT-Web: Notes/Item/AI/deploy-chatgpt-web.md
      - Deploy ChatGPT-Next-Web: Notes/Item/AI/deploy-chatgpt-next-web.md
    - Bind:
      - Yum Install Bind: Notes/Item/yum-install-bind.md
      - Set Master/Slave: Notes/Item/set-master-slave.md
    - Cert:
      - Apply Certificate Using Certbot: Notes/Item/apply-certificate-using-certbot.md
    - Cockpit:
      - Yum Install Cockpit: Notes/Item/yum-install-cockpit.md
    - Confluence:
      - Deploy Confluence On Compose: Notes/Item/deploy-confluence-on-compose.md
    - Container:
      - Deploy Private Registry Server: Notes/Item/Container/deploy-private-registry-server.md
      - Docker Bridge Iptables Disabled: Notes/Item/Container/docker-bridge-iptables-disabled.md
      - Dockerfile Build Jenkins-BlueOcean: Notes/Item/Container/dockerfile-build-jenkins-blueocean.md
      - Dockerfile Build OpenJDK8u327(1001): Notes/Item/Container/dockerfile-build-openjdk8u327.md
      - Dockerfile Build OpenJDK8u327-font(1001): Notes/Item/Container/dockerfile-build-openjdk8u327-font.md
      - Install Container1.6.8 On CentOS: Notes/Item/Container/install-container1.6.8-on-centos.md
      - Install Docker On Rocky: Notes/Item/Container/install-docker-on-rocky.md
      - Install Docker On Ubuntu: Notes/Item/Container/install-docker-on-ubuntu.md
    - Crontab:
      - Docker Execution Error: Notes/Item/Crontab/docker-execution-error.md
    - GitLab:
      - Deploy GitLab15 On Compose: Notes/Item/GitLab/deploy-gitlab15-on-compose.md
    - Harbor:
      - Deploy Harbor2.7 On Compose: Notes/Item/Harbor/deploy-harbor2.7-on-compose.md
    - Hugo:
      - Deploy Blog On Hugo: Notes/Item/Hugo/deploy-blog-on-hugo.md
    - Jenkins:
      - Deploy Jenkins-Blueocean On Compose: Notes/Item/Jenkins/deploy-jenkins-blueocean-on-compose.md
    - MkDocs:
      - Beauty Board: Notes/Item/MkDocs/beauty-board.md
      - Deploy MkDocs On Docker: Notes/Item/MkDocs/deploy-mkdocs-on-docker.md
      - Set Script Push Code: Notes/Item/MkDocs/set-script-push-code.md
    - RabbitMQ:
      - Deploy HA-RabbitMQ: Notes/Item/RabbitMQ/deploy-ha-rabbitmq.md
      - Install RabbitMQ On CentOS: Notes/Item/RabbitMQ/install-rabbitmq-on-centos.md
      - Start Missing Erlang: Notes/Item/RabbitMQ/start-missing-erlang.md
      - Use Helm Deploy Bitnami-RabbitMQ: Notes/Item/RabbitMQ/use-helm-deploy-bitnami-rabbitmq.md
      - Use Helm Deploy HA-RabbitMQ: Notes/Item/RabbitMQ/use-helm-deploy-ha-rabbitmq.md
      - Use Helm Deploy NFS & HA-RabbitMQ: Notes/Item/RabbitMQ/use-helm-deploy-nfs-ha-rabbitmq.md
      - Use Nginx Set HA-RabbitMQ: Notes/Item/RabbitMQ/use-nginx-set-ha-rabbitmq.md
      - Use Operator Deploy HA-RabbitMQ: Notes/Item/RabbitMQ/use-operator-deploy-ha-rabbitmq.md
      - Use RPM Install RabbitMQ On CentOS: Notes/Item/RabbitMQ/use-rpm-install-rabbitmq-on-centos.md
      - Use Statefulset Deploy HA-RabbitMQ: Notes/Item/RabbitMQ/use-statefulset-deploy-ha-rabbitmq.md
    - Redis:
      - Install Redis6 On CentOS(Gcc4.8.5): Notes/Item/Redis/install-redis6-on-centos-1.md
      - Install Redis6 On CentOS(Gcc9.5.0): Notes/Item/Redis/install-redis6-on-centos-2.md
      - StartUp Error: Notes/Item/Redis/startup-error.md
    - RuoYi:
      - Deploy RuoYi Cloud On CentoOS: Notes/Item/RuoYi/deploy-ruoyi-cloud-on-centos.md
      - Deploy RuoYi SpingBoot On CentOS: Notes/Item/RuoYi/deploy-ruoyi-springboot-on-centos.md
      - Deploy RuoYi Vue On CentOS: Notes/Item/RuoYi/deploy-ruoyi-vue-on-centos.md
    - Seata:
      - Deploy Seata On CentOS: Notes/Item/Seata/deploy-seata-on-centos.md
    - Sentinel:
      - Deploy Sentinel On CentOS: Notes/Item/Sentinel/deploy-sentinel-on-centos.md
    - SonarQube:
      - Deploy SonarQube8.9 On CentOS: Notes/Item/SonarQube/deploy-sonarqube8.9-on-centos.md
      - Deploy SonarQube9.8 On Compose: Notes/Item/SonarQube/deploy-sonarqube9.8-on-compose.md
    - Tomcat:
      - Deploy Tomcat: Notes/Item/Tomcat/deploy-tomcat.md
      - Deploy Tomcat On Docker: Notes/Item/Tomcat/deploy-tomcat-on-docker.md
    - VsFtpd:
      - Deploy VsFtpd: Notes/Item/VsFtpd/deploy-vsftpd.md
    - WireGuard:
      - Deploy WG-Easy: Notes/Item/WireGuard/deploy-wg-easy.md
      - Deploy WG On CentOS7: Notes/Item/WireGuard/deploy-wg-on-centos7.md
      - Set Network Transit: Notes/Item/WireGuard/set-network-transit.md
    - Wordpress:
      - Deploy WordPress On Docker: Notes/Item/Wordpress/deploy-wordpress-on-docker.md
      - Meter Display Error: Notes/Item/Wordpress/meter-display-error.md
  - System:
    - Notes/System/index.md
    - ARM-RPI:
      - Deploy Ubuntu-Server On RPI: Notes/System/ARM-RPI/deploy-ubuntu-server-on-rpi.md
    - GNU-Arch:
      - Install ArchLinux: Notes/System/GNU-Arch/install-archlinux.md
      - Install ArchLinux-i3: Notes/System/GNU-Arch/install-archlinux-i3.md
      - Install ArchLinux-i3wm: Notes/System/GNU-Arch/install-archlinux-i3wm.md
    - GNU-CentOS:
      - Install Libzip: Notes/System/GNU-CentOS/install-Libzip.md
      - Install FFmpeg: Notes/System/GNU-CentOS/install-ffmpeg.md
      - Set The NIC To ETH0: Notes/System/GNU-CentOS/set-the-nic-to-eth0.md
      - Set Sudo Permissions: Notes/System/GNU-CentOS/set-sudo-permissions.md
      - Set Dual IP Proxy Forwarding: Notes/System/GNU-CentOS/set-dual-ip-proxy-forwarding.md
      - Solve RAR Decompression: Notes/System/GNU-CentOS/solve-rar-decompression.md
      - Solve Cmake No Found: Notes/System/GNU-CentOS/solve-cmake-no-found.md
      - Solve Install Error On RPM: Notes/System/GNU-CentOS/solve-install-error-on-rpm.md
      - Update Not Upgrade Kernel: Notes/System/GNU-CentOS/update-not-upgrade-kernel.md
      - Upgrade Kernel Use RPM: Notes/System/GNU-CentOS/upgrade-kernel-use-rpm.md
      - Upgrade OpenSSL3: Notes/System/GNU-CentOS/upgrade-openssl3.md
      - Upgrade Make3.82: Notes/System/GNU-CentOS/upgrade-make3.82.md
      - Upgrade Glibc2.28: Notes/System/GNU-CentOS/upgrade-glibc2.28.md
      - Upgrade Gcc&Glibc-0: Notes/System/GNU-CentOS/upgrade-gcc-glibc-0.md
      - Upgrade Gcc&Glibc-1: Notes/System/GNU-CentOS/upgrade-gcc-glibc-1.md
      - Upgrade Gcc&Glibc-2: Notes/System/GNU-CentOS/upgrade-gcc-glibc-2.md
      - Yum Install GCC: Notes/System/GNU-CentOS/yum-install-gcc.md
      - Yum Install JQ: Notes/System/GNU-CentOS/yum-install-jq.md
      - Yum Install Git: Notes/System/GNU-CentOS/yum-install-git.md
      - Yum Install Lynis: Notes/System/GNU-CentOS/yum-install-lynis.md
      - Yum Install Chrony: Notes/System/GNU-CentOS/yum-install-chrony.md
      - Yum Install Google-Authenticator: Notes/System/GNU-CentOS/yum-install-google-authenticator.md
    - GNU-PVE:
      - PVE Fake Death Handing: Notes/System/GNU-PVE/pve-fake-death-handing.md
      - PVE Hardware Info: Notes/System/GNU-PVE/pve-hardware-info.md
      - PVE8.x Changes Source: Notes/System/GNU-PVE/pve8.x-changes-source.md
      - PVE8.x Remove Subscription: Notes/System/GNU-PVE/pve8.x-remove-subscription.md
    - GNU-Rocky:
      - Cannot Modify SSH Port: Notes/System/GNU-Rocky/cannot-modify-ssh-port.md
      - Rocky9 Changes Source: Notes/System/GNU-Rocky/rocky9-changes-source.md
    - GNU-Ubuntu:
      - Change The NIC to ETH0: Notes/System/GNU-Ubuntu/change-the-nic-to-eth0.md
      - Ubuntu24 Basic Config: Notes/System/GNU-Ubuntu/ubuntu24-basic-config.md
      - Ubuntu24 Changes Source: Notes/System/GNU-Ubuntu/ubuntu24-changes-source.md
      - Ubuntu24 On Br_Netfilter: Notes/System/GNU-Ubuntu/ubuntu24-on-br_netfilter.md
    - MS-Win:
      - Home Edition Open Gpedit: Notes/System/MS-Win/home-edition-open-gpedit.md
      - Security Policies Prevent Guest Access: Notes/System/MS-Win/security-policies-prevent-guest-access.md
  - Software:
    - Notes/Software/index.md
    - Chrome:
      - Enable Parallel Downloading: Notes/Software/Chrome/enable-parallel-downloading.md
      - Solve Err_Cert_Invalid: Notes/Software/Chrome/solve-err_cert_invalid.md
      - Solve Neterr_Cert_Authority_Invalid: Notes/Software/Chrome/solve-neterr_cert_authority_invalid.md
    - Nas-Qnap:
      - Changes Docker Source: Notes/Software/Nas-Qnap/changes-docker-source.md
      - Deploy VaultWarden On Qnap: Notes/Software/Nas-Qnap/deploy-vaultwarden-on-qnap.md
    - NoteBook:
      - EliteBook Recore Display Memory: Notes/Software/NoteBook/elitebook-recore-display-memory.md
      - NoteBook Battery Status: Notes/Software/NoteBook/notebook-battery-status.md
      - NoteBook Skips Internet Activation(Win11): Notes/Software/NoteBook/notebook-skips-internet-activation-win11.md
    - Security:
      - HuoRong Manslaughter Explorer: Notes/Software/Security/huorong-manslaughter-explorer.md
    - VMware:
      - WMware Pro Free: Notes/Software/VMware/vmware-pro-free.md
    - VsCode:
      - Remote Compilation: Notes/Software/VsCode/remote-compilation.md
      - Set Background Wallpaper: Notes/Software/VsCode/set-background-wallpaper.md
  - Fun:
    - Comic:
      - Deploy Tachidesk: Notes/Fun/Comic/deploy-tachidesk.md
    - Services:
      - Build Private Services: Notes/Fun/Services/build-private-services.md
  - Giscus:
    - giscus.md
